### ISSUE TITLE
wordMapEnv not found if maps is in Imports

### ISSUE THREAD

**Issue by javigzz** [ropensci/paleobioDB#12]
It seems something related to the dataset 'wordMapEnv' from 'maps' package, not being loaded. 
See the traceback and error:

```
Error in get(dbname) : object 'worldMapEnv' not found
In addition: Warning message:
In data(list = dbname, envir = environment()) :
     data set ‘worldMapEnv’ not found

7: get(dbname)
6: Sys.getenv(get(dbname))
5: paste(Sys.getenv(get(dbname)), database, sep = "")
4: maptype(database)
3: map(plot = F)
2: .extract.rank.specie(data, res)
1: pbdb_map_richness(canidae, res = 3, rank = "species")
```

Aparently (and I don't know why), this dataset is loaded (attached?) when the package is in 'Depends'. Maybe if it was possible to explicitly load a dataset form another package, we could load it when the package is initialized (and no need to be in 'Depends'). Something like `data(maps:wordMapEnv)`. Couldn't find the way. Is it possible in any way?

**Comment by BroVic** [comment]
Hi.

I just stumbled (or actually found) this convo, and am logging this comment to state that 2 years later, we're still getting this error.

**Comment by SaraVarela** [comment]
Thanks for the feedback @BroVic Please, feel free to collaborate with us and send a pull request if you find a  nice solution :-)

**Comment by BroVic** [comment]
@SaraVarela Okay, will do :)

**Comment by castroinsua** [comment]
I have moved all dependencies back to Imports and I cannot reproduce the same error, so it seems that something must have changed.
