### ISSUE TITLE
Handling of spaces in taxon names

### ISSUE THREAD

**Issue by willgearty** [ropensci/paleobioDB#16]
It seems the package is having trouble parsing spaces in the taxa names I am giving it.
For example:
`pbdb_taxon(name="Bison bison", show=c("app"), vocab="pbdb")`
returns
>    oid   gid typ rnk   nam   nm2        sta    par  rid ext
>1 42751 42751 txn   5 Bison bison belongs to 234360 6294   1

whereas
`pbdb_taxon(name="Bison+bison", show=c("app"), vocab="pbdb")`
returns what I was looking for:
>  taxon_no orig_no record_type    rank  taxon_name     status parent_no reference_no is_extant firstapp_ea firstapp_la lastapp_ea lastapp_la
>1    44511   44607       taxon species Bison bison belongs to     42751        12782         1       2.588      0.0117     0.0117          0

I know that the API can handle spaces (parsed as %20):
`http://paleobiodb.org/data1.1/taxa/single.txt?name=Bison%20bison&show=app`
and the second case above:
`http://paleobiodb.org/data1.1/taxa/single.txt?name=Bison+bison&show=app`
returning the same results in both cases.
So I'm not sure what the problem in the code is, but I think it would be great if both of these cases were handled the same way.
Thanks in advance,
Will

**Comment by SaraVarela** [comment]
Hi Will, 

Thanks for the feedback! I will check this during the weekend. It seems that you are getting different results by adding the +, not only that the field names are expanded in one version and contracted in the other, which is strange. 

I will let you know,
Cheers!
Sara

**Comment by willgearty** [comment]
Hi Sara,
Yes, I found that quite odd as well.

**Comment by SaraVarela** [comment]
Hi Will, 

We fixed this issue :-)

From now, you can use the github version of the package for your analysis as follows:

install.packages("devtools")
library(devtools)
install_github("ropensci/paleobioDB")
library(paleobioDB)

pbdb_taxon(name="Bison bison", show=c("app"), vocab="pbdb")

These changes will be on the CRAN version of the package in the future, 

best, 
Sara

**Comment by willgearty** [comment]
Fantastic, thanks for the fix!
