### ISSUE TITLE
Error: C stack usage  129122144 is too close to the limit

### ISSUE THREAD

**Issue by dandaman** [ropensci/paleobioDB#17]
Hi,

after successfully using the paleobioDB web API to query ~3000 entries using Perl,  I stumbled over the ropensci packages and am amazed by the possibilities for integration of multiple services. Thanks for providing these very useful tools!

I'd like to use paleobioDB to query all fossil occurrences for a set of 2952 taxonomic names:

length(clas)
[1] 2952

head(clas)
[1] "Abies"               "Abies lasiocarpa"    "Acacia"  
[4] "Acacia argyrophylla" "Acacia pycnantha"    "Acacieae"   

I've tried the entire list in one call but that was rejected due to POST size limit. SO I'm using the following statements:

get_occs<-function(x,k) {
        y<-ifelse(x+k>length(clas),length(clas),x+k)
        pbdb_occurrences(limit="all",base_name=clas[x:y], vocab="pbdb",show=c("coords", "phylo", "ident"))
}

occs<-do.call(rbind,lapply(seq(1,length(clas),by=10),function(x) get_occs(x,10)))

It runs for quite some time and then crashes with the following error:
Error: C stack usage  129122144 is too close to the limit

occs is empty after that. It's not the only (R) process running on the machine. I've increased the stack size with ulimit -s:

Cstack_info()["size"]
    size 
15938355 

My next try would be to split the list into several independent chunks that are queried independently.  I want to make sure I'm not just doing something wrong or the pbdb_occurrences behavior is not expected. When I used the occs service with perl I queried single base_names in a loop over the same ~ 3k entries without running into problems ...

This is my sessionInfo()

R version 3.1.2 (2014-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C  
 [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=en_US.UTF-8  
 [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8  
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C  
 [9] LC_ADDRESS=C               LC_TELEPHONE=C  
[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] paleobioDB_0.3 maps_2.3-9     raster_2.3-24  sp_1.0-17     

loaded via a namespace (and not attached):
 [1] colorspace_1.2-4 grid_3.1.2       gtools_3.4.1     lattice_0.20-29 
 [5] munsell_0.4.2    plyr_1.8.1       Rcpp_0.11.3      RCurl_1.95-4.1  
 [9] rjson_0.2.15     scales_0.2.4

**Comment by SaraVarela** [comment]
Hi Daniel, 

When you use the parameter base_name, the pbdb_occurrences will give you all the occurrences from all taxa included in your query. This means, that if you pass "Acacia", you will donwload all the species included in Acacia, and all the records from the genus Acacia. If you pass Acacieae, you are going to have all the occurrences from all the species from all the genus of Acacieae, and all the records identified as any Acacieae genus, and all the records identified as Acacieae.
So, do not ask for "Acacia", and then "Acacia argyrophylla" and then "Acacieae", because you are going to have a lot of duplicated records. 

You can use this function and just pass the name of the highest taxonomic rank that you need. For instance: Acacieae

Let me know if this works for you, 

best, 
Sara

**Comment by DomBennett** [comment]
Hi Sara,

A friend of mine was having a similar issue with the stack error message being reported. His code was:

```r
library(paleobioDB)
NA_mammals <- pbdb_occurrences(base_name='Mammalia', continent='NOA', ident='latest',
limit='all', interval='Neogene', timerule='contain',
show=c('ident', 'phylo', 'coords', 'loc'))
```

Yet running for just primates is successful. So it cannot just be a query error.
```r
NA_primates <- pbdb_occurrences(base_name='Primates', continent='NOA', ident='latest',
limit='all', interval='Neogene', timerule='contain',
show=c('ident', 'phylo', 'coords', 'loc'))
```

On digging into the code, I realised the error was to do with the `strsplit()` function in the `.extract_response_body()` function. Perhaps an error related to the size of `response`? If I'm right, all this function is essentially doing is removing the header line of the URL response and then checking the status code. In which case, the use of regex isn't required when searching for `'\r\n\r\n'`, meaning `fixed=TRUE` in `strsplit()` could be used. (For some reason for a large string performing a regexp search can lead to an overstack error? I haven't fully delved into what is causing the error.)

As a quick patch, I did this:

```r
# extract response body patch
.extract_response_body <- function(response) {
  sp <- strsplit(response, "\r\n\r\n", fixed=TRUE)[[1]]
  header <- sp[[1]]
  status <- substring(header, 10, 12)
  body <- sp[[2]]
  if (status != "200") {
    stop(sprintf("Error in API response. The server returned a status %s, which indicates that \n\t\t\tsomething went wrong with your request. \r\nIn order to debug the problem you may find\n\t\t\tusefull information in the following server response:\r\n%s", 
                 status, body))
  }
  body
}
assignInNamespace(x='.extract_response_body', value=.extract_response_body,
                  ns='paleobioDB')
NA_mammals <- pbdb_occurrences(base_name='Mammalia', continent='NOA', ident='latest',
limit='all', interval='Neogene', timerule='contain',
show=c('ident', 'phylo', 'coords', 'loc'))
```

Am I right in thinking this? Or have I missed something?

In the off chance that I have been helpful, I [forked the repo](https://github.com/DomBennett/paleobioDB), made the change and tested it locally. All of your tests passed! I can make a fork request, if that would be helpful. But then it's such a small change you could update it yourself!

Hope this is helpful and best wishes,
Dom

**Comment by SaraVarela** [comment]
Hi @DomBennett 
thanks for the feedback and your fix. I will check this now :-)
best wishes, 
Sara

**Comment by javigzz** [comment]
@DomBennett please do that pull request and we'll merge it right away.
Thanks for the patch!
