### ISSUE TITLE
pbdb_temp_range() and associated functions misidentify species-level occurrences assigned formally to genera as a single 'species' and assign an incorrect label

### ISSUE THREAD

**Issue by dwbapst** [ropensci/paleobioDB#19]
I was recently examining species-level range output from `paleobioDB`, as I describe [here](http://nemagraptus.blogspot.com/2015/02/how-do-we-treat-fossil-age-data-dates.html) and [here](http://nemagraptus.blogspot.com/2015/02/what-is-right-way-to-identify-unique.html) and discovered an issue with how `pbdb_temp_range` identifies unique species-level taxa, which would also impact functions based on this function, like `pbdb_richness` and `pbdb_orig_ext`.

To illustrate the issue, first consider this example with a graptolite genus:

```r
library(paleobioDB)
dicelloData<-pbdb_occurrences(limit="all", base_name="Dicellograptus", show=c("phylo","ident"),vocab="pbdb")
pbdb_temp_range(dicelloData, rank="species", do.plot=FALSE)
```

```
##                              max   min
## Dicellograptus alector     471.8 443.4
## Dicellograptus anceps      455.8 443.7
## Dicellograptus ornatus     453.0 443.4
## Dicellograptus complanatus 453.0 443.7
```

It finds four species. One of these, however, *Dicellograptus alector* is quite odd.

```r
dicelloData[dicelloData$species_name=="alector",c("early_age","late_age")]
```

```
##       early_age late_age
## 1:87      460.9    449.5
## 1:88      449.5    443.7
## 1:187     456.1    449.5
## 1:188     456.1    449.5
## 1:189     456.1    449.5
## 1:190     456.1    449.5
## 1:191     456.1    449.5
## 1:197     449.5    443.7
```

First, we can see that *D. alector* is being given an older age than any of its occurrences. Furthermore...

```r
dicelloData[dicelloData$species_name=="alector",c("taxon_no","matched_name")]
```

```
##       taxon_no   matched_name
## 1:87     33650 Dicellograptus
## 1:88     33650 Dicellograptus
## 1:187    33650 Dicellograptus
## 1:188    33650 Dicellograptus
## 1:189    33650 Dicellograptus
## 1:190    33650 Dicellograptus
## 1:191    33650 Dicellograptus
## 1:197    33650 Dicellograptus
```

We can see that these occurrences are attached to a formal taxon ID with the `matched_name = "Dicellograptus"`, the taxon listing for the entire genus. If we look at how species are identified in [the code here](https://github.com/ropensci/paleobioDB/blob/master/R/pbdb_temporal_functions.R#L72-80) we can see that `taxon_no` is used to identify them from all occurrences with a `taxon_rank = species`. So let's look at all the occurrences with this "taxon_no" and a species-level rank:

```r
dicelloData[dicelloData$taxon_no==33650 & dicelloData$taxon_rank=="species",
            c("taxon_name","species_name","matched_name")]
```

```
##                               taxon_name species_name   matched_name
## 1:87       Dicellograptus alector n. sp.      alector Dicellograptus
## 1:88       Dicellograptus alector n. sp.      alector Dicellograptus
## 1:107             Dicellograptus gurleyi      gurleyi Dicellograptus
## 1:108           Dicellograptus mensurans    mensurans Dicellograptus
## 1:109         Dicellograptus sextans cf.      sextans Dicellograptus
## 1:123         Dicellograptus sextans cf.      sextans Dicellograptus
## 1:125             Dicellograptus sextans      sextans Dicellograptus
## 1:126           Dicellograptus vagus cf.        vagus Dicellograptus
## 1:127            Dicellograptus intortus     intortus Dicellograptus
## 1:128         Dicellograptus sextans cf.      sextans Dicellograptus
## 1:129             Dicellograptus sextans      sextans Dicellograptus
## 1:131             Dicellograptus sextans      sextans Dicellograptus
## 1:133         Dicellograptus sextans cf.      sextans Dicellograptus
## 1:134           Dicellograptus vagus cf.        vagus Dicellograptus
## 1:136     Dicellograptus divaricatus cf.  divaricatus Dicellograptus
## 1:137        Dicellograptus caduceus cf.     caduceus Dicellograptus
## 1:138     Dicellograptus forchammeri cf.  forchammeri Dicellograptus
## 1:139        Dicellograptus intortus cf.     intortus Dicellograptus
## 1:140     Dicellograptus moffatensis cf.  moffatensis Dicellograptus
## 1:141             Dicellograptus sextans      sextans Dicellograptus
## 1:142             Dicellograptus sextans      sextans Dicellograptus
## 1:143             Dicellograptus sextans      sextans Dicellograptus
## 1:144     Dicellograptus divaricatus cf.  divaricatus Dicellograptus
## 1:145        Dicellograptus intortus cf.     intortus Dicellograptus
## 1:146  Dicellograptus intermedius n. sp.  intermedius Dicellograptus
## 1:148         Dicellograptus sextans cf.      sextans Dicellograptus
## 1:150           Dicellograptus vagus cf.        vagus Dicellograptus
## 1:151         Dicellograptus divaricatus  divaricatus Dicellograptus
## 1:152 Dicellograptus russonioides n. sp. russonioides Dicellograptus
## 1:153  Dicellograptus intermedius n. sp.  intermedius Dicellograptus
## 1:154          Dicellograptus johnstrupi   johnstrupi Dicellograptus
## 1:155          Dicellograptus johnstrupi   johnstrupi Dicellograptus
## 1:157             Dicellograptus morrisi      morrisi Dicellograptus
## 1:159             Dicellograptus sextans      sextans Dicellograptus
## 1:160         Dicellograptus gurleyi cf.      gurleyi Dicellograptus
## 1:161             Dicellograptus sextans      sextans Dicellograptus
## 1:162         Dicellograptus elegans cf.      elegans Dicellograptus
## 1:163         Dicellograptus morrisi cf.      morrisi Dicellograptus
## 1:164             Dicellograptus sextans      sextans Dicellograptus
## 1:165          Dicellograptus smithi cf.       smithi Dicellograptus
## 1:166             Dicellograptus sextans      sextans Dicellograptus
## 1:167          Dicellograptus smithi cf.       smithi Dicellograptus
## 1:168             Dicellograptus sextans      sextans Dicellograptus
## 1:169             Dicellograptus sextans      sextans Dicellograptus
## 1:170        Dicellograptus caduceus cf.     caduceus Dicellograptus
## 1:171             Dicellograptus sextans      sextans Dicellograptus
## 1:172             Dicellograptus gurleyi      gurleyi Dicellograptus
## 1:173          Dicellograptus smithi cf.       smithi Dicellograptus
## 1:174             Dicellograptus sextans      sextans Dicellograptus
## 1:176             Dicellograptus sextans      sextans Dicellograptus
## 1:179         Dicellograptus divaricatus  divaricatus Dicellograptus
## 1:180             Dicellograptus sextans      sextans Dicellograptus
## 1:181         Dicellograptus divaricatus  divaricatus Dicellograptus
## 1:182         Dicellograptus divaricatus  divaricatus Dicellograptus
## 1:183             Dicellograptus sextans      sextans Dicellograptus
## 1:184         Dicellograptus elegans cf.      elegans Dicellograptus
## 1:187             Dicellograptus alector      alector Dicellograptus
## 1:188             Dicellograptus alector      alector Dicellograptus
## 1:189             Dicellograptus alector      alector Dicellograptus
## 1:190             Dicellograptus alector      alector Dicellograptus
## 1:191         Dicellograptus alector cf.      alector Dicellograptus
## 1:192     Dicellograptus ? angulatus cf.    angulatus Dicellograptus
## 1:193     Dicellograptus ? angulatus cf.    angulatus Dicellograptus
## 1:194       Dicellograptus angulatus cf.    angulatus Dicellograptus
## 1:195         Dicellograptus elegans cf.      elegans Dicellograptus
## 1:197             Dicellograptus alector      alector Dicellograptus
## 1:198         Dicellograptus elegans cf.      elegans Dicellograptus
## 1:199         Dicellograptus elegans cf.      elegans Dicellograptus
## 1:212           Dicellograptus flexuosus    flexuosus Dicellograptus
## 1:218               Dicellograptus minor        minor Dicellograptus
## 1:220               Dicellograptus minor        minor Dicellograptus
## 1:224               Dicellograptus minor        minor Dicellograptus
## 1:225               Dicellograptus minor        minor Dicellograptus
## 1:230               Dicellograptus minor        minor Dicellograptus
## 1:235               Dicellograptus minor        minor Dicellograptus
## 1:236             Dicellograptus tumidus      tumidus Dicellograptus
## 1:237            Dicellograptus turgidus     turgidus Dicellograptus
## 1:238           Dicellograptus mirabilis    mirabilis Dicellograptus
## 1:240               Dicellograptus minor        minor Dicellograptus
## 1:241             Dicellograptus tumidus      tumidus Dicellograptus
## 1:242            Dicellograptus turgidus     turgidus Dicellograptus
## 1:245               Dicellograptus minor        minor Dicellograptus
## 1:247               Dicellograptus minor        minor Dicellograptus
## 1:249               Dicellograptus minor        minor Dicellograptus
## 1:250               Dicellograptus minor        minor Dicellograptus
## 1:251               Dicellograptus minor        minor Dicellograptus
## 1:254               Dicellograptus minor        minor Dicellograptus
## 1:256               Dicellograptus minor        minor Dicellograptus
## 1:258               Dicellograptus minor        minor Dicellograptus
## 1:260               Dicellograptus minor        minor Dicellograptus
## 1:262               Dicellograptus minor        minor Dicellograptus
```

What's happening here is that a large number of informal species (i.e. species that didn't have a formal listing in the PBDB) were entered under the `taxon_no` of their genus. We can see these listed as "Species lacking formal opinion data" [here](http://paleobiodb.org/cgi-bin/bridge.pl?a=checkTaxonInfo&taxon_no=33650&is_real_user=1).

So, filtering to species-level occurrences via `taxon_rank` and then sorting by `taxon_no` can result in mistakingly grouping a number of informally entered species that are formally assigned to their genus as a single species-level taxon with an exaggerated number of occurrences assigned to it.

But why does the label *Dicellograptus alector* get assigned to it?

Again, looking at [the code here](https://github.com/ropensci/paleobioDB/blob/master/R/pbdb_temporal_functions.R#L72-80), we can see the function `match()` is used to find `genus_name` and `species_name` which are then combined into a single species label.  Unfortunately, the use of `match()` returns the first and only the first match in a list, so the assigned species-label is an arbitrary function of whatever species comes first in a table of occurrences. This results in the mistaken reporting of *Dicellograptus alector* from occurrence data formally assigned to *Dicellograptus*.

We can test this by randomly shuffling to resort the table of occurrences:

```r
set.seed(1)
d2<-dicelloData[sample(1:nrow(dicelloData)),]
pbdb_temp_range(d2, rank="species", do.plot=FALSE)
```

```
##                               max   min
## Dicellograptus russonioides 471.8 443.4
## Dicellograptus anceps       455.8 443.7
## Dicellograptus ornatus      453.0 443.4
## Dicellograptus complanatus  453.0 443.7
```

And we get a totally new species name for what was labeled *D. alector*.

**Comment by dwbapst** [comment]
FYI
I discuss the issue of identifying unique species, and review the large number of taxonomic variables that can play a role, in a blog post [here](http://nemagraptus.blogspot.com/2015/02/identifying-unique-species-in.html).

**Comment by SaraVarela** [comment]
Hi David, 

It is nice to have a quality check of the functions of the package! 
thanks for all your work on this and for discovering these issues. 
Do you want to help us in fixing these bugs? or in explaining the users these problems?
It will be nice if you join the team. 
We are planning to program more functions and make a new version of the package during the Autumn, so maybe you want to enter in the discussions about which functions should be programmed and how to solve the different problems that will appear. 

Let me know what you think, 
best, 

Sara

**Comment by dwbapst** [comment]
Sara,

At the moment, I'm happy to just provide you with the feedback you need to deal with these issues. I've found I have some 'skill' at breaking scientific software by accident and then figuring out 'why' it is breaking, but fixing such issues can be hard and requires considerable thought and energy that I'm afraid I'm not available to give right now. Having encountered these issues, I felt it was required of me to notify your team. This concern of mine also developed into an extended consideration of the taxonomic structure of the PBDB itself, which isn't well-documented, and hence my lengthy blog post.

I obviously have my own ideas on how to solve the unique species question, but I don't think my solution will necessarily work for `paleobioDB`. Right now, I really just want to get to the point where I can safely convert PBDB data to a format useable by my package `paleotree`, as I have some research depending on this goal. I would recommend you consider Matt Clapham's `cleanTaxa` (which is released under CC0) as a potential starting point, as I think it would probably serve the purpose of correctly separating out taxa in `paleobioDB` with minimum modification.

I will continue to keep an eye on `paleobioDB` and you can rest assured that I'll keep doing my best to try breaking it from the user-side.

-Dave

**Comment by SaraVarela** [comment]
Hi David, 

I changed one of the parameters of the function to avoid this issue. Now, it looks for the matched_rank, that is the "reviewed" taxonomic rank, and not the initial identified taxonomic rank. 
Please, use the github version of the package (I will upload this to the CRAN in one month).

Anyway, one thing that is important to understand here is that the functions that we programmed to explore the data do not need to be the same of other packages (or the API). Thus, in the last version of this function what we were doing was analyzing the raw data (the data as it was when entered to the database). Now, we are analizing the "reviewed" fields (that it seems that is the same that they did for constructing some fields in the database, so you should have the same values now).

I hope that this is working for you, 
if not, you can directly use the downloaded data using pbdb_occurrences and program a function to analyze it as you need for your package. With pbdb_occurrences you can take all the info that you need from the database.  

let me know if now it works for you,
best, 

Sara

**Comment by dwbapst** [comment]
Hi Sara!

Well, first, let's see what sort of a difference it made for my pretty little dicellograptids:

```r
# library(devtools)
# install_github("ropensci/paleobioDB")
library(paleobioDB) 
```

```
## Loading required package: raster
## Loading required package: sp
## Loading required package: maps
```

```r
dicelloData<-pbdb_occurrences(limit="all", base_name="Dicellograptus", show=c("phylo","ident"),vocab="pbdb")
pbdb_temp_range(dicelloData, rank="species", do.plot=FALSE)
```

```
##                              max   min
## Dicellograptus anceps      455.8 443.7
## Dicellograptus ornatus     453.0 443.4
## Dicellograptus complanatus 453.0 443.7
```
Okay, so you're now using `matched_rank` which I would agree is better bet than `taxon_rank` for identifying 'formal'/'reviewed' (whatever we want to call them!) unique species in the PBDB. In this case, that means only the formally identified species get listed.

However, you're using `taxon_no` to find the unique species at `match_rank = species`, but that means you'll be reporting multiple synonymized taxa as separate taxa. Is that intentional? In this case it doesn't make a difference, but it would if their original `taxon_name` didn't match their formal `matched_name`.

Here's an example using the brachiopod species *Acosarina minuta*:

```r
library(paleobioDB)
acoData<-pbdb_occurrences(limit="all", base_name="Acosarina minuta", show=c("phylo","ident"),vocab="pbdb")
pbdb_temp_range(acoData, rank="species", do.plot=FALSE)
```

```
##                          max    min
## Acosarina indica       303.7 251.30
## Acosarina dorsisulcata 290.1 252.17
## Orthotichia indica     290.1 254.17
## Dalmanella indica      279.3 252.17
## Orthis indica          272.3 252.17
## Acosarina minuta       268.8 251.30
## Sunacosarina campana   265.1 259.90
## Acosarina kanmerai     265.1 259.90
## Kotlaia capillosa      259.9 254.17
## Orthotichia minuta     259.9 254.17
```

But if we look at `matched_no`, we see there is only a single 'formal' species listed:

```r
unique(acoData$matched_no)
```

```
## [1] 125301
```
Independently,  I would be wary of matching and pasting `genus_name` and `species_name` to create taxon names. Even if you use `matched_no` instead of `taxon_name`, you could end up with the wrong label for a taxon. Furthermore, this can still produce circumstances where the taxon names output by the function is dependent on the ordering of rows in the data table. Perhaps use `matched_name` instead?

I noticed also looking [at your code](https://github.com/ropensci/paleobioDB/blob/master/R/pbdb_temporal_functions.R#L91) that you are using `genus_name` (the original genus name assigned to an occurrence) instead of `genus` (the formal genus name) for identifying genera in `pbdb_temp_range`. If you do switch to using `matched_no` rather than `taxon_no` for species-level assessments, I'd suggest switching to `genus` so that all taxa identified as unique by that function always are referring to the formal taxa IDs. For example, consider this example with the *A. minuta* data, where there is a single 'formal'/'reviewed' species, but six genera get listed:

```r
pbdb_temp_range(acoData, rank="genus", do.plot=FALSE)
```

```
##                max    min
## Acosarina    303.7 251.30
## Orthotichia  290.1 254.17
## Dalmanella   279.3 252.17
## Orthis       272.3 252.17
## Sunacosarina 265.1 259.90
## Kotlaia      259.9 254.17
```

For what its worth, all the other taxonomic levels called by 'pbdb_temp_range' refer to the 'formal'/'reviewed' PBDB taxonomy, so these suggestions would at least make the output consistent in providing the same type of output.

Maybe something to think about?

-Dave

**Comment by SaraVarela** [comment]
Hi David, 

those fields where not there last year when we programmed the functions, so we couldn't use them. 

I already changed the temporal functions, so now our functions for exploring the data of the paleobioDB use matched names and matched numbers instead of raw names and raw taxon numbers. 

cheers, 
Sara

**Comment by dwbapst** [comment]
Checking it out with my above examples and...


```r
library(paleobioDB)
```

```
## Loading required package: raster
## Loading required package: sp
## Loading required package: maps
```

```r
dicelloData<-pbdb_occurrences(limit="all", base_name="Dicellograptus", show=c("phylo","ident"),vocab="pbdb")
pbdb_temp_range(dicelloData, rank="species", do.plot=FALSE)
```

```
##                              max   min
## Dicellograptus anceps      455.8 443.7
## Dicellograptus ornatus     453.0 443.4
## Dicellograptus complanatus 453.0 443.7
```


```r
library(paleobioDB)
acoData<-pbdb_occurrences(limit="all", base_name="Acosarina minuta", show=c("phylo","ident"),vocab="pbdb")
pbdb_temp_range(acoData, rank="species", do.plot=FALSE)
```

```
##                    max   min
## Acosarina minuta 303.7 251.3
```

```r
unique(acoData$matched_no)
```

```
## [1] 125301
```


```r
pbdb_temp_range(acoData, rank="genus", do.plot=FALSE)
```

```
##             max   min
## Acosarina 303.7 251.3
```

Ah, yes, that looks good! I'd suggest modifying the documentation to note that the function (now) only returns taxa with formal IDs in the database, but I'd say we can close this ticket!
