### ISSUE TITLE
Apparent bug in taxon_name, and exclude_id functions

### ISSUE THREAD

**Issue by JuanCarrillo** [ropensci/paleobioDB#20]
Hello, 
When downloading some data, I wanted to exclude the records of some taxonomic groups from my querry and I noticed several issues:

1. I saw you have an exclude_id function but no an exclude_name function.
2. In order to find the numeric identifier for the taxon I wanted to exclude (e.g. Cetacea), I tried to use the taxon_name function and then look for the taxon_no (tid)

test<-pbdb_occurrences(taxon_name="Cetacea", continent="NOA",limit="all",max_ma=5)

but I got the following message

Error in API response. The server returned a status 500, which indicates that 
                        something went wrong with your request. 

In order to debug the problem you may find
                        usefull information in the following server response:

{ "status_code": 500,
"errors": ["A server error occurred.  Please contact the server administrator."] }

If instead of taxon_name I used the base_name function, then it works but I still dont know the taxon number of Cetacea, but of the different subtaxa within Cetacea, which is not what I want.

test<-pbdb_occurrences(base_name="Cetacea", continent="NOA",limit="all",max_ma=5)

3.If I try to use the exclude_id function to exclude the first record of my previous querry 
( Physeterula sp.   taxon number= 36808) 

test<-pbdb_occurrences(taxon_name="Cetacea", continent="NOA",limit="all",max_ma=5, exclude_id=36808)

I got the same error message.

Thanks a lot for your assintance and help,

regards, 

Juan

**Comment by SaraVarela** [comment]
Hola Juan, 

I am looking at your code, and it seems that this is not a problem of our R package but of the paleobioDB database. 

look, if you ask directly to the database (not in R, but directly through their webpage), you have the same error: 
http://paleobiodb.org/data1.1/occs/list.txt?taxon_name=Cetacea&interval=Miocene&show=loc,time

it seems that something happens with the taxon_name parameter and that they do not allow to query the database using taxon_name. Which is weird. This could be a temporary failure/change. I will contact them to ask about this issue. 

best, 

Sara

by the way, Cetacea indet seems to be id 36652 (if this is what you wanted)

**Comment by JuanCarrillo** [comment]
Hola Sara,

Thanks a lot for your reply. Could you please let me know once the PBDB 
people give you a response about this issue? I will be checking 
periodically, as I am in need of this data, or otherwise do you of any 
other way to find out about the taxon id numbers of the PBDB?
Cetacea is only one of few that I need.

best,
Juan

On 02.03.2015 14:16, Sara Varela wrote:
>
> Hola Juan,
>
> I am looking at your code, and it seems that this is not a problem of 
> our R package but of the paleobioDB database.
>
> look, if you ask directly to the database (not in R, but directly 
> through their webpage), you have the same error:
> http://paleobiodb.org/data1.1/occs/list.txt?taxon_name=Cetacea&interval=Miocene&show=loc,time
>
> it seems that something happens with the taxon_name parameter and that 
> they do not allow to query the database using taxon_name. Which is 
> weird. This could be a temporary failure/change. I will contact them 
> to ask about this issue.
>
> best,
>
> Sara
>
> by the way, Cetacea indet seems to be id 36652 (if this is what you 
> wanted)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ropensci/paleobioDB/issues/20#issuecomment-76709592>.
>

-- 
Juan D. Carrillo
Paläontologisches Institut und Museum
Universität Zürich
Karl Schmid-Strasse 4
CH-8006 Zürich
Phone:+41 044 634 21 47
Email: juan.carrillo@pim.uzh.ch

**Comment by SaraVarela** [comment]
Hola Juan, 

better use pbdb_taxon function or pbdb_taxa (if you need more than one taxon). 

pbdb_taxon (name="Cetacea", vocab="pbdb")

pbdb_taxa (name=c("Canidae", "Cetacea"), vocab="pbdb")

the first column will be the taxon_no

cheers, 
Sara
