### ISSUE TITLE
Thematic maps in R

### ISSUE THREAD

**Issue by AlexanderIntoR** [ropensci/paleobioDB#26]
An interesting example within Shiny is [http://shiny.rstudio.com/tutorial/lesson5/]. I like to implement it for instance for the Postal codes in the Netherlands [http://www.imergis.nl/asp/47.asp] and create a simple thematic map. 

library(maptools)
readshp<-readShapeSpatial("C:/R/census-app/ESRI-PC4-2015R1.shp")

The variable on which I like to create a map is added in the Dbasefile behind the shape, but after:

map("readshp", fill = TRUE, col = fills, 
    resolution = 0, lty = 0, projection = "polyconic", 
    myborder = 0, mar = c(0,0,0,0))

R shows the error:

> Error in get(dbname) : object 'readshpMapEnv' not found

How can we fix this?

**Comment by SaraVarela** [comment]
Hi Alexander, 

this is not an issue of our R package. 
You can ask programming doubts in stackoverflow
http://stackoverflow.com/questions/tagged/?tagnames=r&sort=active
best, 
Sara

**Comment by AlexanderIntoR** [comment]
Hi Sara,

It is maybe rather simple, but how can you question on stackoverflow; is there a button?

Kind regards

Alexander

Van: Sara Varela [mailto:notifications@github.com]
Verzonden: woensdag 16 maart 2016 12:17
Aan: ropensci/paleobioDB <paleobioDB@noreply.github.com>
CC: Bruijns, Alexander (A.F.) <alexander.bruyns@cendris.com>
Onderwerp: Re: [paleobioDB] Thematic maps in R (#26)


Hi Alexander,

this is not an issue of our R package.
You can ask programming doubts in stackoverflow
http://stackoverflow.com/questions/tagged/?tagnames=r&sort=active
best,
Sara
