### ISSUE TITLE
Proposed inclusion of a `stringsAsFactors` param to `pbdb_ocurrences`

### ISSUE THREAD

**Issue by gaballench** [ropensci/paleobioDB#27]
The `pbdb_occurrences` function does not allow a parameter `stringsAsFactors` to be set during high-level call, despite the function `as.data.frame` used in the `.make_data_frame` function (line [79](https://github.com/ropensci/paleobioDB/blob/master/R/network.R#L79) in `network.R`) allows to use such parameter. I think that relying on `default.stringsAsFactors()` does not allow easy customization of the output from `pbdb_occurrences` unless the user explicitly changes the default of `stringsAsFactors`, what in programatic use may affect other functions. An alternative would be:

``` r
options(stringsAsFactors = FALSE) # turn off sAF
pbdbp_occurrences(...)
options(stringsAsFactors = TRUE) # back to default sAF
```

However, allowing a way to declare sAF as `FALSE` could make easier the customization of the output in the call to `pbdb_occurrences`. I noted that a potential issue would involve the way that `.implode_to_string` is used since a plain usage of `stringsAsFactors` as a parameter results in an obvious error, since the latter function would treat that parameter as part of the query for the PBDB API.

Maybe detection of the `stringsAsFactors` parameter during call to `.implode_to_string` before looping (e.g., around line [47](https://github.com/ropensci/paleobioDB/blob/master/R/pbdb_querys.R#L47) in `pbdb_querys.R`) could change the default of `stringsAsFactors` in the function environment, then remove it from the `l` parameter list to be imploded, and then reset the default of `stringsAsFactors` to the default value:

``` r
# around line 47 in pbdb_querys.R
if ("stringsAsFactors" %in% names(l)) {
  options(stringsAsFactors = FALSE) # setting sAF to FALSE
  l["stringsAsFactors"] <- NULL # removing sAF param before implosion
}
```

Maybe it would not be necessary to reset sAF to `TRUE` since such change would occur inside the environment of `pbdb_occurrences`, so it might not affect the global behavior of such global option.

**Comment by psmits** [comment]
I'm no where near an expert on the paleobioDB code base but changing options seems not great from a safe/no unwanted side effects perspective.

The JSON query is converted into an R data frame using the `.make_data_frame` function in `network.R` (start line 60). the as.data.frame could be modified to to take user input at a higher level (e.g. `pbdb_occurrences`) through `...`. This option would overload the original `...` call cause that is supposed to be for API arguments and fixing that would require a creative solution.

What you can also do is change the data frame to a tibble or manually change all the strings to factors; `dplyr::mutate_if` would be the perfect function for this.

**Comment by castroinsua** [comment]
Since R 4.0.0, `stringsAsFactors` has a default value of `FALSE`, which is what most people expect. If someone wants to convert some columns from the returned data frame to factors, I think it is more practical to do that outside of any function this package provides. I think I can close this issue if there are no objections.
