### ISSUE TITLE
pbdb_temp_range and pbdb_richness on data downloaded through web interface

### ISSUE THREAD

**Issue by Bukoplot** [ropensci/paleobioDB#28]
Hi, and hope this is the right place to ask this question. First, many thanks for this package. It is really a great tool. But I seem to have a silly problem using the pbdb_temp_range() and pbdb_richness() with data downloaded through the PBDB interface (and I do need to use that). I get the following error:

Error in colnames(temporal_range) <- c("max", "min") :   object 'temporal_range' not found

Even though I specified the temporal extent. Am I doing something wrong, or perhaps there is a simple way to fix it?

Many thanks!
Emilia

**Comment by SaraVarela** [comment]
Hi Emilia, 
sorry for the late reply. I was on maternity leave :-)
I think that the problem that you had should be related with the names of the variables that you are downloading from the PBDB interface. in the API they might  have different names and for that reason our function doesnt work. You can check the names of our variables downloading a short example using our package, and then, change the names of your variables to be exactly the same before using pbdb_temp_range(). 
We are now uploading a new version of the package to the cran, so please, load it from github

install.packages("devtools")
library(devtools)
install_github("ropensci/paleobioDB")
library(paleobioDB)


I hope that this works, 
best regards, 
Sara

**Comment by javigzz** [comment]
Closing since it is related to passing unexpected data to the function. In upcoming merge I am improving the error messages thrown by that function should this happen again.
