### ISSUE TITLE
Not all occurences returned by `pbdb_occurrences`

### ISSUE THREAD

**Issue by NickCrouch** [ropensci/paleobioDB#42]
Hi,
I noticed that not all of the occurrences on the pbdb website are returned when using `pbdb_occurences`. For example, running:
`pbdb_occurrences(limit="all", vocab="pbdb", taxon_name="Prognathodon", show="ident")`
Returns 21 occurences, where as searching for the same genus on PBDB returns 62 occurrences. Any ideas why this might be?
Thanks

I'm using paleobioDB_0.6.0

**Comment by SaraVarela** [comment]
Hi @NickCrouch 

try with base_name (which includes everything, all species within the genus), not taxon_name

base_name | Return only records associated with the specified taxonomic name(s), including all subtaxa and synonyms. You may specify multiple names, separated by commas. You may append one or more exclusions to any name, using the ^ character. For example, Osteichthyes^Tetrapoda would select the fish excluding the tetrapods.
-- | --
taxon_name | Return only records associated with the specified taxonomic name(s), including any synonyms. You may specify multiple names, separated by commas. Names may include wildcards, but if more than one name matches then only the one with the largest number of occurrences in the database will be used.

or check here for more details: 
https://paleobiodb.org/data1.2/occs/list_doc.html

abrazos,
Sara

**Comment by NickCrouch** [comment]
Oh! perfect, thank you very much
