### ISSUE TITLE
pbdb_richness() xlab overlaps with ticks

### ISSUE THREAD

**Issue by RussellGrayxd** [ropensci/paleobioDB#43]
the xlab "million years before present" overlaps with the ticks over 3 digits when plotted

**Comment by SaraVarela** [comment]
thanks! added to the todo list! :-)

**Comment by castroinsua** [comment]
I think https://github.com/ropensci/paleobioDB/commit/1afb5b07300f4cf6b15cb531a227428527c36c5d fixes this bug.
