### ISSUE TITLE
Move readme figures into ./man/figures

### ISSUE THREAD

**Issue by jeroen** [ropensci/paleobioDB#44]
See https://docs.ropensci.org/paleobioDB/ and this comment from Hadley: https://github.com/ropensci/rotemplate/issues/19#issuecomment-506315565

You can also have a look where other packages store `readme.md` figures:

 - https://github.com/ropensci/tidyhydat/
 - https://github.com/ropensci/drake/

**Comment by javigzz** [comment]
Hi! looks like this was fixed at some point (https://github.com/ropensci/paleobioDB/commit/985afad52b18af7c6acd459b7c1ff5fdf9f39398) and forgot to close this issue.
Thanks @jeroen
