### ISSUE TITLE
API no longer linked

### ISSUE THREAD

**Issue by mwyatt272** [ropensci/paleobioDB#45]
Hello! The PBDB recently moved to a different server and I am guessing that is the cause of the error message?

> canis_quaternary<- pbdb_occurrences (limit="all", base_name="Canis", interval="Quaternary", show=c("coords", "phylo", "ident"))
Error in .extract_response_body(response) : 
  Error in API response. The server returned a status 301, which indicates that 
			something went wrong with your request. 
In order to debug the problem you may find
			usefull information in the following server response:
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by SaraVarela** [comment]
Hi, now it seems that it is working. They had some issues with the paleobioDB server, maybe it is happening again. 
let me know if it works now. 
thanks for the feedback, 
Sara

**Comment by javigzz** [comment]
@mwyatt272 Please install the new version in master and try again. I've just merged a patch that should solve the issue.
Looks like they no longer support `http` as the package expected, but `https`

**Comment by mwyatt272** [comment]
It is working now! Thanks!
