### ISSUE TITLE
None of the functions to query the database work anymore

### ISSUE THREAD

**Issue by RussellGrayxd** [ropensci/paleobioDB#49]
I have code from this package that has worked for years, and now none of it does. 

The vignette/documentation code also doesn't work, everytime I use the pbdb_occurrences() function it returns:

Error in .extract_response_body(response) : 
  Error in API response. The server returned a status 301, which indicates that 
			something went wrong with your request. 
In order to debug the problem you may find
			usefull information in the following server response:
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

I assume this means the API has a different path now that hasn't been added into the package API wrapper functions or something???

**Comment by SaraVarela** [comment]
Thanks Russell, 
we will fix it as soon as possible! 
best, 
Sara

**Comment by javigzz** [comment]
Hello @RussellGrayxd, this bug was already fixed with the last version (was also reported in #45).
Please try with last version (0.7.0) either from CRAN or from this repo and let me know.
Regards
Javier
