### ISSUE TITLE
Maps don't work anymore

### ISSUE THREAD

**Issue by RussellGrayxd** [ropensci/paleobioDB#50]
So I've updated to the latest version, as the previous ones wouldn't connect with the API and query data anymore... And now that data can be queried but the mapping functions are all wonky, and the coordinates all seem to have major issues. Again this is code and data that I have queried hundreds if not thousands of times over the years since the package was put out. So I'm assuming something went wrong within the database itself. Maybe someone added or removed something from the coordinate pairs and it damaged them all?

**example:**

library(paleobioDB)

# query data
palocc <- pbdb_occurrences(limit="all", vocab="pbdb",
                           base_name=c("Boidae", "Colubridae", "Elapidae"), show=c("phylo", "ident", "coords","attr", "app", "size", "nav", "time", "crmod"))

# map data
pbdb_map(palocc)

**Comment by castroinsua** [comment]
This problem was due to the API returning the coordinates as character strings, and passing this values to functions that expected numeric values. I think this bug is fixed now.
