### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by sckott** [ropensci/paleobioDB#6]
Some or all tests rely on internet connection so how to deal with that wrt CRAN? Some options
- Check for an internet connection and don't perform tests that require a connection. I haven't tried this. @ropensci/owners What's an elegant way to do this? Perhaps

``` coffee
test_that("some test", {
    # check for internet connection 
    res <- check_connection()
    if(!res){ NULL }  else { # proceed if connection found, just pass NULL if no connection
        tests...
    }
})
```
- Just have CRAN ignore tests by adding `test/`to the `.Rbuildignore` file. I sometimes do this 
- Others

**Comment by javigzz** [comment]
Finally closing this. I've moved all the tests to an ad-hoc script triggered by travis and kept them out the CRAN check.
